### ISSUE TITLE
Tooltip with Disabled controlled select component

### ISSUE THREAD

**Issue by hect1c** [atomiks/tippyjs-react#184]
Hey,

First I would like to say this is a really great package, thanks for this.

I'm able to get this working really well in my project except when I have an input that is disabled using a controlled component like react-select.

I'm a bit stuck on trying to get this work, being able to still display the tooltip even when my select dropdown or input is disabled, how can I achieve this as I basically want to primarily display the tooltip when the input or select dropdown is disabled.

I've created a codesandbox to demonstrate what I have in a small version: https://codesandbox.io/s/condescending-agnesi-p3ypc.

As you can see I'm using react-select and have created a separate tooltip component. When my select is not disabled the tooltip works fine but once it's disabled it is not showing. I noticed this issue https://github.com/atomiks/tippyjs-react/issues/123 but tried this and it was not working. Hope you may be able to provide some suggestions on this, thanks.

**Comment by KubaJastrz** [comment]
I don't see any tooltip when I change to `isDisabled={false}` either. What is the desired outcome?

**Comment by hect1c** [comment]
Hey,

Sorry wasn't clear but when you set `isDisabled={false}` and you hover over the select input for a bit you will see some text appear just above it, there's no styling. I've just tried it and it works. 

The desired outcome is for this to still appear when `isDisabled={true}`

**Comment by hect1c** [comment]
Were you able to see it now?

**Comment by KubaJastrz** [comment]
Hi, I've reproduced it. Sorry for the delay.

Few things:
- You are attaching Tooltip onto `.pq-select__single-value`, so you need to select something before you can see the Tooltip
- Tippy doesn't work when reference element is `disabled`, so adding `<span disabled>` around the reference element doesn't make any sense. It needs to always be enabled.
- Even when you actually select something and then set `CreatableSelect` to `isDisabled={true}`, Tooltip doesn't show up. This is because `.css-14jk2my-container` (wrapper from `react-select`) has `pointer-events: none` when it is disabled. This prevents Tippy from reading `mouseenter` events because they simply are never fired.

**Comment by atomiks** [comment]
I think `pointer-events` is the key issue.
