### ISSUE TITLE
tooltip not floating near child component

### ISSUE THREAD

**Issue by elya158** [atomiks/tippyjs-react#189]
After migrating to the new version (I was using version 1.1.1) I'm having issues with the tooltip floating near the child component, instead the target seems to be the parent.
I want to be able to hover over the child element and the tooltip will open near it.
The parent has the position relative css property and the child has position absolute css property. Note that I have to leave these css properties for my app.
I created a sandbox to simulate my issue:

[https://codesandbox.io/s/interesting-firefly-69nz1?file=/src/App.js](url)

**Comment by elya158** [comment]
See sandbox above, thanks

**Comment by atomiks** [comment]
It doesn't seem to be a problem of the parent, but just the layout/CSS itself. The parent node is not affected by the absolute child, and the Tippy isn't getting added to the child but the wrapper span. I don't know how it worked in Popper v1 to be honest but I would avoid this pattern due to a11y problems anyway. If you hover the span tag, you'll see it's not wrapping the child's layout. Just apply Tippy to the child and use `forwardRef`.
