### ISSUE TITLE
Use `ReactNode` for content instead of `ReactChild`

### ISSUE THREAD

**Issue by mskelton** [atomiks/tippyjs-react#210]
The `ReactNode` type is preferrable over the `ReactChild` type as it allows all types which ReactChild does in addition to boolean, null, or undefined which are perfectly valid.  Limiting to ReactChild makes it difficult in TypeScript as types which return undefined (e.g. i18next `t` function are not valid as the `content` prop of `<Tippy>`.

I'd be happy to open a PR if you are okay with this change.

**Comment by atomiks** [comment]
Yes that seems ok

**Comment by KubaJastrz** [comment]
`ReactChild` was chosen deliberately, to prevent empty tooltips:
![2020-05-09_17-02-14](https://user-images.githubusercontent.com/6443113/81477220-e6f56880-9216-11ea-9d9f-dc8b0ed30a79.png)
```tsx
<Tippy content={null}>
	<button>test</button>
</Tippy>
```
```ts
tippy('button', {
  content: null
})
```


Of course, passing `null` and `undefined` values will still work, because `React.createElement` accepts them, and `ReactNode` will more accurately represent this.

If we want to go back to the old types, we should also update [the core lib](https://github.com/atomiks/tippyjs/blob/bf975605aa694e1cb1ad82e964b926830243ac80/src/types.ts#L7).

**Comment by atomiks** [comment]
@KubaJastrz since `content` is now optional, and empty string creates the same problem, I'm not sure if that would be relevant anyore

**Comment by atomiks** [comment]
@KubaJastrz since `content` is now optional, and an empty string creates the same problem, I'm not sure if that would be relevant anymore 🤔

**Comment by KubaJastrz** [comment]
I guess the tippy philosophy is to let users take care of the validation problems, so maybe it will make some things easier. I remember that I had to do some workarounds when passing null content even though Tippy was disabled.
