### ISSUE TITLE
Jest error: TypeError: React.forwardRef is not a function

### ISSUE THREAD

**Issue by horacioh** [atomiks/tippyjs-react#225]
when start testing my app, I'm getting this error from Jest:
```
  ● Test suite failed to run

    TypeError: React.forwardRef is not a function

      21 | 
      22 |       for (var key in source) {
    > 23 |         if (Object.prototype.hasOwnProperty.call(source, key)) {
         |                             ^
      24 |           target[key] = source[key];
      25 |         }
      26 |       }

      at forwardRef (../../node_modules/@tippyjs/react/src/forwardRef.js:5:3)
      at ../../node_modules/@tippyjs/react/src/index.js:8:16
      at ../../node_modules/@tippyjs/react/dist/tippy-react.umd.js:2:66
      at Object.<anonymous> (../../node_modules/@tippyjs/react/dist/tippy-react.umd.js:5:2)
```

I'm using the [Tippy version with props](https://github.com/atomiks/tippyjs-react#-props), is this a known issue?

thanks in advance!

**Comment by horacioh** [comment]
nevermind... I think this is something else!
sorry!

**Comment by rafaelsorto** [comment]
@horacioh how did you solve this? I am having the same React.forwardRef is not a function in Next.JS with Jest

**Comment by darbymanning** [comment]
@rafaelsorto I had this issue, so I ended up mocking the library in Jest, In case this is useful for anyone else:

```js
jest.mock("@tippyjs/react", () => ({
  __esModule: true,
  default: jest.fn(),
}));
```

**Comment by gosukiwi** [comment]
I'm also getting this issue. I don't think this should be closed. Mocking doesn't work either.

**Comment by rafaelsorto** [comment]
I was able to solve my issue by mocking it as @JChiaramonte7 explained and it worked for me. Maybe your mocking is not actually overriding tippy ?

I somehow think it has to do with the project and jest settings because I created a new project trying to recreate this issue and I couldn't. If you start a brand new create react app project and add @tippyjs/react with some tests  it doesn't complain. The issue I was having was specifically in a nextjs project.
