### ISSUE TITLE
Warning after upgrade from v4.0.2 to v4.0.4.

### ISSUE THREAD

**Issue by yury-tyshkevich** [atomiks/tippyjs-react#232]
Warning in console after upgrade from v4.0.2 to v4.0.4.

Server Side Rendering! Perhaps the problem is in createPortal()

![image](https://user-images.githubusercontent.com/57856695/85222774-7bcab480-b3c6-11ea-8e67-7ba66216b265.png)

**Comment by atomiks** [comment]
> Perhaps the problem is in createPortal()

Yes it is. https://reactjs.org/docs/react-dom.html#hydrate

We removed the `mounted && createPortal()` call to fix a bug — https://github.com/atomiks/tippyjs-react/issues/227 — but this appears to have caused some issues.

Any ideas to fix the bug and also remove the warning is welcome with a PR. The warning is not actually a problem since tippy content is never seen on the server, but it's certainly annoying. The previous technique also caused 2 renders which made the component slower, so hopefully we can avoid that...

**Comment by KubaJastrz** [comment]
I'm pretty sure the `mounted && createPortal()` is the recommended approach in this case. What is needed to remove the warning is to have the same DOM output both on the server and client, and it seems like the only way to do that reliably is to skip first render completely.

Alternatively, we could try to render the tooltip, but I think tippy is not synchronous by nature.

There's also `suppressHydrationWarning` as the last resort 🤷‍♂️

**Comment by atomiks** [comment]
I don't see the warning in the console when using Gatsby tho 🤔

**Comment by atomiks** [comment]
`v4.0.5`
