### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by basicuserindahouse** [atomiks/tippyjs-react#283]
Hi there!
We use **sentry.io** to detect errors in our **next.js** app and I see this error message for a long time:

![image](https://user-images.githubusercontent.com/67904992/105478288-115b5900-5cb4-11eb-8d41-6cc86678ed7f.png)

According to these messages it is generated by **tippyjs-react** plugin:

![image](https://user-images.githubusercontent.com/67904992/105480593-ffc78080-5cb6-11eb-9810-100bd1944fa5.png)

We can't replay this error manually in local development or prod version of our app but we are concerned about its presence in **sentry.io**. 
Browser and version here:

![image](https://user-images.githubusercontent.com/67904992/105686055-da7d8100-5f07-11eb-9647-22d2a9133ba4.png)

Also I found a similar bug here https://github.com/atomiks/tippyjs-react/issues/139 
But we use component as a `<Tippy...> ` exactly as written in the solution and we still have an error. 

Any ideas?

Thanks!

**Comment by atomiks** [comment]
Maybe https://stackoverflow.com/a/54644168

**Comment by atomiks** [comment]
Need bug repro to help further.

**Comment by bbonamin** [comment]
In case it helps anybody, I've been hitting this issue a lot when Tippy has to interact with other scripts that modify the DOM after being rendered (not common or recommended for React obviously, but sometimes needed for legacy reasons... in our case we're using the classic Google Translate widget. 

Interestingly, this only happens on when calling `<Tippy... />` with text nodes as values for the `content=` prop.

The fix was to wrap all the text nodes with a JSX element.

e.g. before:
```javascript
<Tippy content="Hello world" >
<a href="#">Hello world"</a>
</Tippy>
```

e.g. after:
```javascript
<Tippy content={<span>"Hello world"</span>} >
<a href="#">Hello world"</a>
</Tippy>
```

ugly, but it seems to work as expected.

[This link helped me understand why](https://github.com/facebook/react/issues/11538#issuecomment-390386520)
